# Generated by Django 3.1.7 on 2021-03-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_okved',
            field=models.ForeignKey(help_text='Основной ОКВЭД', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.okved'),
        ),
    ]
