# Generated by Django 3.1.7 on 2021-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_main_okved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='okved',
            field=models.ManyToManyField(related_name='okved_id', to='companies.Okved'),
        ),
    ]
