# Generated by Django 3.1.7 on 2021-03-15 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_okved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего изменения'),
        ),
    ]
